[package]
name = "competitive"
version = "0.1.0"
authors = ["to-omer <toomerhs@gmail.com>"]
edition = "2018"

[lib]
doc-scrape-examples = true

[dependencies]
codesnip = { version = "0.2.1", package = "codesnip_attr", features = [
    "check",
] }
