[package]
name = "competitive"
version = "0.1.0"
authors = ["to-omer <toomerhs@gmail.com>"]
edition = "2018"

[dependencies]
cargo-snippet = "0.6"
snippet = { path = "../snippet" }

[features]
default = []
snippet_nightly = []
