[languages.rs]
compile = "cargo build --release"
execute = "\"bash -c 'basename {path} .rs | xargs -I @@@ cargo run --release --quiet --bin @@@'\""
bundle = "false"
list_attributes = "sed 's|^// verify-helper: ||; t; d' {path}"
list_dependencies = "true"
