[languages.rs]
compile = "cargo build --release"
execute = "cargo run --quiet --bin $(basename {path} .rs) --release"
bundle = "false"
list_attributes = "sed 's|^// verify-helper: ||; t; d' {path}"
list_dependencies = "true"
