[package]
name = "snippet_core"
version = "0.1.0"
authors = ["to-omer <toomerhs@gmail.com>"]
edition = "2018"

[dependencies]
syn = { version = "1", features = ["full", "extra-traits", "visit", "visit-mut"] }
proc-macro2 = "1"
quote = "1"
thiserror = "1.0"
