name: CI

on:
  schedule:
    - cron: '0 0 */6 * *'
  push:
    branches:
      - master
  pull_request:


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - 1.42.0-x86_64-unknown-linux-gnu
          - stable-x86_64-unknown-linux-gnu
          - nightly-x86_64-unknown-linux-gnu

    name: Build (${{ matrix.toolchain }})
    runs-on: ubuntu-18.04
    env:
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
      SCCACHE_CACHE_SIZE: 1.5G
      SCCACHE_DIR: /home/runner/.cache/sccache

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install sccache (ubuntu-latest)
      env:
        LINK: https://github.com/mozilla/sccache/releases/download
        SCCACHE_VERSION: v0.2.15
      run: |
        SCCACHE_FILE=sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl
        mkdir -p $HOME/.local/bin
        curl -L "$LINK/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
        mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
        chmod +x $HOME/.local/bin/sccache
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Cache cargo and sccache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          /home/runner/.cache/sccache
        key: cargo-${{ runner.os }}-${{ matrix.toolchain }}
        restore-keys: cargo-${{ runner.os }}-

    - name: Start sccache server
      run: sccache --start-server    

    - name: Setup `${{ matrix.toolchain }}`
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true
        profile: minimal
        components: rustfmt, clippy

    - name: cargo-fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: cargo-clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --workspace --lib --tests --no-deps

    - name: cargo-build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --workspace --lib --tests

    - name: cargo-test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --workspace --no-fail-fast

    - name: Stop sccache server
      run: sccache --stop-server || true


  snippet:
    name: Snippet
    runs-on: ubuntu-18.04
    env:
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
      SCCACHE_CACHE_SIZE: 1.5G
      SCCACHE_DIR: /home/runner/.cache/sccache

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install sccache (ubuntu-latest)
      env:
        LINK: https://github.com/mozilla/sccache/releases/download
        SCCACHE_VERSION: v0.2.15
      run: |
        SCCACHE_FILE=sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl
        mkdir -p $HOME/.local/bin
        curl -L "$LINK/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
        mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
        chmod +x $HOME/.local/bin/sccache
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Cache cargo and sccache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          /home/runner/.cache/sccache
        key: cargo-${{ runner.os }}-stable-x86_64-unknown-linux-gnu
        restore-keys: cargo-${{ runner.os }}-

    - name: Start sccache server
      run: sccache --start-server    

    - name: Setup `stable-x86_64-unknown-linux-gnu`
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable-x86_64-unknown-linux-gnu
        override: true
        profile: minimal
        components: rustfmt

    - name: cargo-install codesnip
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: codesnip
      env:
        CARGO_TARGET_DIR: target

    - name: Snippet Verification
      uses: actions-rs/cargo@v1
      with:
        command: codesnip
        args: --target=crates/competitive/src/lib.rs --filter-item=test --cfg=nightly verify --verbose

    - name: Stop sccache server
      run: sccache --stop-server || true


  verify:
    strategy:
      fail-fast: false
      matrix:
        job-id: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

    name: Verify
    runs-on: ubuntu-18.04
    env:
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
      SCCACHE_CACHE_SIZE: 1.5G
      SCCACHE_DIR: /home/runner/.cache/sccache

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install sccache (ubuntu-latest)
      env:
        LINK: https://github.com/mozilla/sccache/releases/download
        SCCACHE_VERSION: v0.2.15
      run: |
        SCCACHE_FILE=sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl
        mkdir -p $HOME/.local/bin
        curl -L "$LINK/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
        mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
        chmod +x $HOME/.local/bin/sccache
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Cache cargo and sccache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          /home/runner/.cache/sccache
        key: cargo-${{ runner.os }}-1.42.0-x86_64-unknown-linux-gnu
        restore-keys: cargo-${{ runner.os }}-

    - name: Start sccache server
      run: sccache --start-server    

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install online-judge-api-client

    - name: Setup `1.42.0-x86_64-unknown-linux-gnu`
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.42.0-x86_64-unknown-linux-gnu
        override: true
        profile: minimal

    - name: Verify
      env:
        RUST_MIN_STACK: 268435456
        RUST_LOG: verify=info
      run: |
        ulimit -s unlimited
        python ./.github/workflows/matrix.py ${{ matrix.job-id }}

    - name: upload artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: artifact/**/*

    - name: Stop sccache server
      run: sccache --stop-server || true


  benchmark:
    strategy:
      fail-fast: false

    name: Benchmark
    runs-on: ubuntu-18.04
    env:
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
      SCCACHE_CACHE_SIZE: 1.5G
      SCCACHE_DIR: /home/runner/.cache/sccache

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install sccache (ubuntu-latest)
      env:
        LINK: https://github.com/mozilla/sccache/releases/download
        SCCACHE_VERSION: v0.2.15
      run: |
        SCCACHE_FILE=sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl
        mkdir -p $HOME/.local/bin
        curl -L "$LINK/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
        mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
        chmod +x $HOME/.local/bin/sccache
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Cache cargo and sccache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          /home/runner/.cache/sccache
        key: cargo-${{ runner.os }}-stable-x86_64-unknown-linux-gnu
        restore-keys: cargo-${{ runner.os }}-

    - name: Start sccache server
      run: sccache --start-server    

    - name: Setup `stable-x86_64-unknown-linux-gnu`
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable-x86_64-unknown-linux-gnu
        override: true
        profile: minimal

    - name: Install Gnuplot
      continue-on-error: true
      run: |
        sudo apt-get install gnuplot

    - name: Benchmark
      env:
        CRITERION_HOME: ./../../target/doc/benchmarks
      run: |
        ulimit -s unlimited
        cargo bench -p competitive --bench criterion

    - name: upload artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: benchmarks
        path: target/doc/benchmarks/**/*

    - name: Stop sccache server
      run: sccache --stop-server || true


  generate-doc:
    needs: [verify, benchmark]
    if: github.ref == 'refs/heads/master'

    name: Generate Doc
    runs-on: ubuntu-18.04
    env:
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
      SCCACHE_CACHE_SIZE: 1.5G
      SCCACHE_DIR: /home/runner/.cache/sccache

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install sccache (ubuntu-latest)
      env:
        LINK: https://github.com/mozilla/sccache/releases/download
        SCCACHE_VERSION: v0.2.15
      run: |
        SCCACHE_FILE=sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl
        mkdir -p $HOME/.local/bin
        curl -L "$LINK/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
        mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
        chmod +x $HOME/.local/bin/sccache
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Cache cargo and sccache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          /home/runner/.cache/sccache
        key: cargo-${{ runner.os }}-nightly-x86_64-unknown-linux-gnu
        restore-keys: cargo-${{ runner.os }}-

    - name: Start sccache server
      run: sccache --start-server    

    - name: Setup `nightly-x86_64-unknown-linux-gnu`
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2021-12-02
        target: x86_64-unknown-linux-gnu
        override: true

    - name: Download artifacts
      uses: actions/download-artifact@v2

    - name: Arrange artifacts
      run: cp -r artifact/* .

    - name: cargo-build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --workspace --lib --features verify_doc

    - name: cargo-doc
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --workspace --no-deps --features verify_doc
      env:
        RUSTDOCFLAGS: --html-in-header util/header.html

    - name: Arrange benchmarks
      run: |
        mkdir target/doc/benchmarks
        cp -r benchmarks/* target/doc/benchmarks

    - name: Arrange doc resources
      run: cp -r util/gh-pages/* target/doc

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAT }}
        publish_dir: ./target/doc

    - name: Stop sccache server
      run: sccache --stop-server || true
