name: verify

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - name: Run test
      run: cargo test --lib

  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job-id: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: pip3 install -U online-judge-api-client
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true

    - name: Run verify
      env:
        RUST_MIN_STACK: 268435456
      run: python matrix.py ${{ matrix.job-id }}
      continue-on-error: true

    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: artifact/**/*

  generate-doc:
    needs: verify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: download artifacts
      uses: actions/download-artifact@v2
    - run: cp -r artifact/* .

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true

    - name: Generate cargo doc
      env:
        RUSTDOCFLAGS: --html-in-header katex-header.html
      run: |
        cargo doc --no-deps --features verify_doc
        cat <<EOT > target/doc/index.html
        <!DOCTYPE html><meta charset="utf-8"><meta http-equiv="refresh" content="0; url=competitive/index.html"><title></title>
        EOT

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAT }}
        publish_dir: ./target/doc
