name: verify

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: pip3 install -U online-judge-api-client
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - name: Set up git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name GitHub
        git config --global user.email noreply@github.com
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git pull github ${GITHUB_REF} --ff-only

    - name: Run test
      run: cargo test

    - name: Run verify
      env:
        RUST_MIN_STACK: 268435456
      run: |
        ulimit -s unlimited
        cargo test --release -- --ignored
      continue-on-error: true

    - name: Commit changes
      run: |
        git commit -a -m "[auto-verifier] verify commit ${GITHUB_SHA}"
        git push github HEAD:${GITHUB_REF}


  doc:
    runs-on: ubuntu-latest
    needs: test
    if: contains(github.ref, 'master')
    steps:
    - uses: actions/checkout@v1
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true

    - name: Generate cargo doc
      run: |
        cargo doc --no-deps
        cat <<EOT > target/doc/index.html
        <!DOCTYPE html><meta charset="utf-8"><meta http-equiv="refresh" content="0; url=competitive/index.html"><title></title>
        EOT

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAT }}
        publish_dir: ./target/doc
